# /* // Completed by Matt Courchaine and Satwik Tadikamalla */
# This file defines the nginx config to serve the frontend application.
# It listens on port 80 and servers all traffic to index.html file.
server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
