# // Completed by Matt Courchaine and Satwik Tadikamalla
# This file defines the name of the helm chart to be deployed for the backend. 
apiVersion: v2
name: backend
description: Helm chart for SWE645 HW3 backend (FastAPI)
type: application
version: 0.1.0
appVersion: "1.0.0"
