# // Completed by Matt Courchaine and Satwik Tadikamalla
# This file sets up the values for front end helm chart. 
# These values are used throughout the rest of the front end helm chart to deploy the pod.
replicaCount: 1

image:
  repository: mcourch/hw3-ui
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30002

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: frontend.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
