replicaCount: 1

image:
  repository: hw3-ui
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: frontend.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
